language: node_js
node_js:
- node
- 6
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn run build
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy:production
  on:
    branch: master
env:
  global:
  - secure: ZTV9kKazCwisWm/szLJnfAb9x/0ChQl1xXmW2r7YalFhLk04IG8Wz56Oty5bb5VMghVNoMeE36zfPAuCbq/dOSqN5DbBCZj1T+55RGed6kN09zw3ClS7WgQ9DbW0GQvEoFU3aBJr3nx9IeZVIAPuxyTG5KGcT8tU63tIsroE9Ix479GJMRt8nEB3w+ZjcV7DHNVdjzlT1sTKoz3jyAVxrcVz0Ut3NSHg12gD9SzslttBNgNZOkKAd0JlTaqU4gmus6oqZGh70ABqmOsaGzSbpUSujwJUnxmuAQ5iGVryf42hcyuMrHzc6SSVH5U/qxAlwAiq/5waH/NoPdvYlFIDoOipYdWuRhfn5vIMyALVADLKOmp/QtQvC0h55Qq+umxxkPck0GvUGwLPg5uh12Ni6RffWSLktveUreBuWuxADW3a4262n3Y9PRglgNqGPrIoK8vCS0EtJOhEcmAljNgADh8PoajDpuYlflpx5A0pQtR/R9mL1z0zsiTb3edBN49e8gWKwq5aP5Y7nS24UvVa/gN8DMTC0wtVZfuSHMhCAgog7b7q32Awcvu1YF0tfJID0mc2NuITp6XQXqqUmG6E3nXR5DXmECZUYdDPlUmvDwHvaILRkFaV1T+Hwvpt8k8HHa9HUb2ScXg0wvK8e2ctcfyLUM5MZ83/HqZySyJk3Mc=
  - secure: I89FpQSQHt8qf/vuNr3BzZm18ZFMfEwkno/DLPszeN3MPyDU0+ELdxXEBRNgrFamUJZkqr8+6WDqvGXhimEuKT9k0mkA8rz+rTM/HsyHDx0iBkskutCQnIMkW1tm7a7WK787KRBsZxgYptfNksDYxnIwTTm7fAHAR2qN3jfmygP86oIqIL096V8Hjtijw6vA0VME6Ke/co0v1VMvC1bpuWQ2R5cryzdSzEgyL+/y2Z6oZDkwcwJd0nGLa4PJUpAMZyjOszku9g+PEOHKa2Vc5wpaTq3eW5uRGTXI7j1V3inzPC6S2NiSueZVQYVlAbp3PAHIMdjrYiJYObCVsABxdJTJIRtfeS0w4fdDhfN5OYz450SFaCTnZg2UGptOs+TLB/YCp0HX4lfM+sWASMypO3obfFE+3ECaLYED/zKIKxbK1WXu0A4oobXWSz94mU9t0zA6r7Wiu+ZZh04e4uGj9IcR7Bn5R6uaMxS8kP8Y10+wqhVNJVn3eyt3uj8UQXdzexgo6BL/FbUP+fFF6mrkpij9KFf8oprJBjiXE+Ayv6N8l2HvF5UZEoJ35LBiyryFDhQhW3l2zWcmn08Q9HZmY++RtaYO/f6vsIziAckVxNapJIDWjonPznYPyap4Gw6odmzBEMFApp3ief9gaiBu7DJVWhMDro1I8IITPcIh51I=
